In [1]:
#importing dependencies
import pandas as pd
import jenkspy
import numpy as np
import json
!pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\arpitas\AppData\Local\anaconda3\Lib\site-packages (3.1.5)
Requirement already satisfied: et_xmlfile in C:\Users\arpitas\AppData\Local\anaconda3\Lib\site-packages (from openpyxl) (1.1.0)

In [95]:
# Read the Excel file into a DataFrame
df = pd.read_csv(r'C:\Users\arpitas\Documents\cpt_local\data\OUT_CSV_MAPDATA_BAYAREA_SANTA_CRUZ_V1.CSV')

In [97]:
# Display the first 5 rows of the DataFrame
df.head()

,UNFORMATTEDAPN,APN,FIPSCODE,ADDRESS,COUNTY,ZIPCODE,ASSDLANDVALUEPERTOTALLANDSQUAREFOOTAGE
0,05535014,055-350-14,6019,", , CA,",FRESNO,,
1,345350004000,345-350-004-000,6107,", , CA,",TULARE,,.0068907790663759
2,925000055,925-000-055,6039,", , CA,",MADERA,,46.89072543618
3,14310010,143-100-10-00-0,6029,"3111 EDISON HWY, BAKERSFIELD, CA, 933072230",KERN,933072230,4.22178596597201
4,011050003000,011-050-003-000,6031,"1415 W LACEY BLVD, HANFORD, CA, 932305906",KINGS,932305906,4.00619235836627

In [99]:
df.dtypes

UNFORMATTEDAPN                            object
APN                                       object
FIPSCODE                                   int64
ADDRESS                                   object
COUNTY                                    object
ZIPCODE                                   object
ASSDLANDVALUEPERTOTALLANDSQUAREFOOTAGE    object
dtype: object

In [101]:
df['ASSDLANDVALUEPERTOTALLANDSQUAREFOOTAGE'] = pd.to_numeric(df['ASSDLANDVALUEPERTOTALLANDSQUAREFOOTAGE'], errors='coerce')

In [103]:
print(df.columns.tolist())

['UNFORMATTEDAPN', 'APN', 'FIPSCODE', 'ADDRESS', 'COUNTY', 'ZIPCODE', 'ASSDLANDVALUEPERTOTALLANDSQUAREFOOTAGE']

In [111]:
# Creating legend categories here based on the categories above and input provided by Lenny
conditions = [
    (df['ASSDLANDVALUEPERTOTALLANDSQUAREFOOTAGE'] < 15),
    (df['ASSDLANDVALUEPERTOTALLANDSQUAREFOOTAGE'] > 15) & (df['ASSDLANDVALUEPERTOTALLANDSQUAREFOOTAGE'] <= 35),
    (df['ASSDLANDVALUEPERTOTALLANDSQUAREFOOTAGE'] > 35) & (df['ASSDLANDVALUEPERTOTALLANDSQUAREFOOTAGE'] <= 60),
    (df['ASSDLANDVALUEPERTOTALLANDSQUAREFOOTAGE'] > 60) & (df['ASSDLANDVALUEPERTOTALLANDSQUAREFOOTAGE'] <= 100),
    (df['ASSDLANDVALUEPERTOTALLANDSQUAREFOOTAGE'] > 100) & (df['ASSDLANDVALUEPERTOTALLANDSQUAREFOOTAGE'] <= 250),
    (df['ASSDLANDVALUEPERTOTALLANDSQUAREFOOTAGE'] > 250)
]
choices = ['1', '2', '3', '4', '5', '6']
default_value = '0'

# Create the new column using np.select()
df['LEGENDCATEGORY'] = np.select(conditions, choices, default=default_value)

df.head()

,UNFORMATTEDAPN,APN,FIPSCODE,ADDRESS,COUNTY,ZIPCODE,ASSDLANDVALUEPERTOTALLANDSQUAREFOOTAGE,LEGENDCATEGORY
1,345350004000,345-350-004-000,6107,", , CA,",TULARE,,0.006891,1
2,925000055,925-000-055,6039,", , CA,",MADERA,,46.890725,3
3,14310010,143-100-10-00-0,6029,"3111 EDISON HWY, BAKERSFIELD, CA, 933072230",KERN,933072230,4.221786,1
4,011050003000,011-050-003-000,6031,"1415 W LACEY BLVD, HANFORD, CA, 932305906",KINGS,932305906,4.006192,1
5,47305002,473-050-02-00-9,6029,"1447 SIERRA HWY, ROSAMOND, CA, 935607248",KERN,935607248,3.575007,1

In [113]:
df = df.dropna(subset=['ASSDLANDVALUEPERTOTALLANDSQUAREFOOTAGE'])
df.head()

,UNFORMATTEDAPN,APN,FIPSCODE,ADDRESS,COUNTY,ZIPCODE,ASSDLANDVALUEPERTOTALLANDSQUAREFOOTAGE,LEGENDCATEGORY
1,345350004000,345-350-004-000,6107,", , CA,",TULARE,,0.006891,1
2,925000055,925-000-055,6039,", , CA,",MADERA,,46.890725,3
3,14310010,143-100-10-00-0,6029,"3111 EDISON HWY, BAKERSFIELD, CA, 933072230",KERN,933072230,4.221786,1
4,011050003000,011-050-003-000,6031,"1415 W LACEY BLVD, HANFORD, CA, 932305906",KINGS,932305906,4.006192,1
5,47305002,473-050-02-00-9,6029,"1447 SIERRA HWY, ROSAMOND, CA, 935607248",KERN,935607248,3.575007,1

In [115]:
df = df.dropna(how='all')  # drops rows where every column is empty

In [117]:
print(df.isnull().sum())

UNFORMATTEDAPN                            0
APN                                       0
FIPSCODE                                  0
ADDRESS                                   0
COUNTY                                    0
ZIPCODE                                   0
ASSDLANDVALUEPERTOTALLANDSQUAREFOOTAGE    0
LEGENDCATEGORY                            0
dtype: int64

In [119]:
df.to_excel('bay-area-santa-cruz.xlsx', index=False)

In [120]:
output = {
    "success": True,
    "data": df.to_dict(orient='records')
}

with open('central-valley.json', 'w') as f:
    json.dump(output, f, indent=2)

print(f"Done! {len(df)} rows converted.")

Done! 122009 rows converted.